services:
  - type: web
    name: anti-phishing-backend
    env: python
    region: ohio # Optional: Choose a region close to your users if possible, or leave default
    plan: free # Use the free tier
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_CREDENTIALS
        sync: false # Do not sync this value from simple settings, it will be set in the dashboard
      - key: PYTHON_VERSION
        value: 3.11.0 # Specify a python version
